### ISSUE TITLE
while bootstarping nomad-server1  it gives error

### ISSUE THREAD

**Issue by thatsk** [oribaldi/consul-cluster#1]
bash: ./setup.sh: /bin/bash^M: bad interpreter: No such file or directory

**Comment by thatsk** [comment]
![error](https://cloud.githubusercontent.com/assets/15324013/25219235/57c4d69c-25cb-11e7-90b7-7e1273ea9b49.png)

**Comment by oribaldi** [comment]
Hey!
Can you try to edit the script for Unix? There is probably an invalid character that came from Windows. Try it and let me know.

**Comment by thatsk** [comment]
i dont see any character.
sending screenshot
![error](https://cloud.githubusercontent.com/assets/15324013/25235552/1760c7e0-2603-11e7-8c92-7231be82917f.png)

**Comment by oribaldi** [comment]
You don't see it, but it is there. Check that the error shows "/bin/bash^M". The "^M" is the invalid character. Can you try editing the file with vi? or if you use Sublime, you can edit the  "line endings" to be "Unix" format.

If you don't manage, I will update the file (and any other with the issue) tonight or tomorrow.

**Comment by thatsk** [comment]
Not working
I have checked .

**Comment by oribaldi** [comment]
I don't get the error on my machine. But I saved the consul/setup.sh file in unix format, using vim. Let me know if the change worked for you.  If you still get the error, try using a command like "dos2unix" or create the file again in Unix.

**Comment by oribaldi** [comment]
Closing issue after no further feedback.
